services:
  postgres:
    image: postgres:latest
    container_name: hotel-rooms-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
